pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/devkelzs/ansible-jenkins-projects'
            }
        }

        stage('Run Ansible') {
            steps {
                dir('ansible') {
                    bat 'wsl ansible-playbook -i inventory.ini playbook.yml'
                }
            }
        }
    }

    post {
        failure {
            echo 'Deployment failed!'
        }
        success {
            echo 'Deployment succeeded!'
        }
    }
}
