pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/devkelzs/ansible-jenkins-projects.git'
            }
        }

        stage('Run Ansible Deployment') {
            steps {
                sh 'ansible-playbook ansible-jenkins-project3/ansible/deploy.yml -i ansible-jenkins-project3/ansible/inventory.yml'
            }
        }
    }
}
