pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/yourusername/my-project.git'
            }
        }

        stage('Run Ansible Deployment') {
            steps {
                sh 'ansible-playbook ansible/deploy.yml -i ansible/inventory.yml'
            }
        }
    }
}
