---
- name: Install python and pip
  apt:
   name: "{{ item }}"
  loop:
    - python3
    - python3-pip

- name: Install Gunicorn and Flask
  pip:
    name:
      - gunicorn
      - flask

- name: Copy applicattion code
  copy:
    src: ../../app/
    dest: /opt/flasK_app/
    mode: '0755'

- name: Start the flask app with Gunicorn
  shell: |
    pkill gunicorn || true
    cd /opt/flasK_app/
    nohub gunicorn -w 3 -b 0.0.0:5000 main:app &