---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Python3, Flask, Gunicorn (apt packages)
  apt:
    name:
      - python3
      - python3-flask
      - gunicorn3
    state: present

- name: Create app directory
  file:
    path: /opt/flask_app
    state: directory
    mode: '0755'

- name: Copy Flask main.py
  copy:
    src: ../app/main.py
    dest: /opt/flask_app/main.py
    mode: '0644'

- name: Start Flask app with Gunicorn
  shell: |
    pkill gunicorn || true
    nohup gunicorn -w 3 -b 0.0.0.0:5000 main:app &
  args:
    chdir: /opt/flask_app
    executable: /bin/bash
